version: '3.9'
services:
  front:
    image: bizgpt/bizgpt-frontend:1.0.0
    build: .
    command: sh -c "node .next/standalone/server.js"
    volumes:
      - .:/app
    container_name: front-${PROJECT_NAME}
    restart: unless-stopped

  nginx:
    image: nginx:1.23.0-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/templates/default.conf.template.standalone:/etc/nginx/templates/default.conf.template:ro
      - ./.next/static:/_next/static
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      # - 80:80
      - ${NGINX_PORT}:${NODE_PORT}
    env_file:
      - .env
    depends_on:
      - front
    container_name: nginx-${PROJECT_NAME}